# Generated by Django 4.2.8 on 2026-04-03 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangSua',
            fields=[
                ('ma_hang_sua', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_hang_sua', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(blank=True, max_length=255)),
                ('dien_thoai', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Hang sua',
                'verbose_name_plural': 'Hang sua',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_kh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_kh', models.CharField(max_length=100)),
                ('gioi_tinh', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nu'), ('O', 'Khac')], max_length=1)),
                ('dia_chi', models.CharField(blank=True, max_length=255)),
                ('dien_thoai', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Khach hang',
                'verbose_name_plural': 'Khach hang',
            },
        ),
        migrations.CreateModel(
            name='LoaiSua',
            fields=[
                ('ma_loai_sua', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_loai_sua', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Loai sua',
                'verbose_name_plural': 'Loai sua',
            },
        ),
        migrations.CreateModel(
            name='Sua',
            fields=[
                ('ma_sua', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_sua', models.CharField(max_length=200)),
                ('quy_cach', models.CharField(blank=True, help_text='Vi du: 180 ml, Thung 48 hop', max_length=100)),
                ('trong_luong', models.PositiveIntegerField(blank=True, help_text='Gram hoac ml', null=True)),
                ('don_vi', models.CharField(blank=True, help_text='g, ml, kg', max_length=10)),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('giam_gia', models.PositiveSmallIntegerField(default=0, help_text='Phan tram giam')),
                ('thanh_phan', models.TextField(blank=True)),
                ('loi_ich', models.TextField(blank=True)),
                ('hinh', models.CharField(blank=True, max_length=255)),
                ('hang_sua', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='san_pham', to='Milk.hangsua')),
                ('loai_sua', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='san_pham', to='Milk.loaisua')),
            ],
            options={
                'verbose_name': 'Sua',
                'verbose_name_plural': 'Sua',
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_hd', models.DateField()),
                ('tri_gia', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Milk.khachhang')),
            ],
            options={
                'verbose_name': 'Hoa don',
                'verbose_name_plural': 'Hoa don',
            },
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Milk.hoadon')),
                ('sua', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Milk.sua')),
            ],
            options={
                'verbose_name': 'Chi tiet hoa don',
                'verbose_name_plural': 'Chi tiet hoa don',
            },
        ),
        migrations.AddConstraint(
            model_name='chitiethoadon',
            constraint=models.UniqueConstraint(fields=('hoa_don', 'sua'), name='uq_cthd_hoa_don_sua'),
        ),
    ]
