# Generated by Django 4.2.8 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Milk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sua",
            name="hinh",
            field=models.ImageField(blank=True, null=True, upload_to="suas/"),
        ),
    ]
