# Generated by Django 4.2.8 on 2026-04-26 04:15

from django.db import migrations, models
import django.db.models.deletion


DANH_MUC_DATA = [
    {
        "ma_danh_muc": "DM01",
        "ten_danh_muc": "Sữa bột trẻ em",
        "mo_ta": (
            "Sữa bột trẻ em là sản phẩm dinh dưỡng được nghiên cứu dành riêng cho giai đoạn "
            "phát triển của trẻ nhỏ, nhằm bổ sung protein, vitamin, khoáng chất, DHA, canxi "
            "và hỗ trợ phát triển toàn diện."
        ),
        "noi_bat": "",
        "loai_sua_id": "LS03",
        "thu_tu": 1,
    },
    {
        "ma_danh_muc": "DM02",
        "ten_danh_muc": "Bột ăn dặm",
        "mo_ta": (
            "Bột ăn dặm là nhóm thực phẩm bổ sung cho trẻ bước vào giai đoạn ăn dặm, giúp bé "
            "làm quen với nhiều hương vị và bổ sung năng lượng, sắt, kẽm cùng vitamin cần thiết."
        ),
        "noi_bat": "",
        "loai_sua_id": None,
        "thu_tu": 2,
    },
    {
        "ma_danh_muc": "DM03",
        "ten_danh_muc": "Sữa bột người lớn",
        "mo_ta": (
            "Sữa bột người lớn phù hợp cho người cần bổ sung dinh dưỡng, năng lượng và vi chất "
            "để duy trì sức bền, cơ bắp và quá trình phục hồi."
        ),
        "noi_bat": "",
        "loai_sua_id": "LS02",
        "thu_tu": 3,
    },
    {
        "ma_danh_muc": "DM04",
        "ten_danh_muc": "Sữa chua ăn",
        "mo_ta": (
            "Sữa chua ăn là sản phẩm lên men giàu lợi khuẩn, hỗ trợ tiêu hóa, tăng hấp thu "
            "dinh dưỡng và phù hợp cho các bữa ăn phụ."
        ),
        "noi_bat": "",
        "loai_sua_id": "LS05",
        "thu_tu": 4,
    },
    {
        "ma_danh_muc": "DM05",
        "ten_danh_muc": "Sữa tươi nguyên chất",
        "mo_ta": (
            "Sữa tươi nguyên chất được lấy từ nguồn sữa tươi, giữ lại hương vị tự nhiên và cung "
            "cấp canxi, protein cùng các vitamin cần thiết cho nhu cầu hằng ngày."
        ),
        "noi_bat": "Best",
        "loai_sua_id": "LS01",
        "thu_tu": 5,
    },
    {
        "ma_danh_muc": "DM06",
        "ten_danh_muc": "Sữa đặc nguyên chất",
        "mo_ta": (
            "Sữa đặc nguyên chất có vị béo đậm, độ ngọt đặc trưng, thường dùng để pha chế đồ uống "
            "hoặc kết hợp trong các món bánh và món tráng miệng."
        ),
        "noi_bat": "",
        "loai_sua_id": "LS04",
        "thu_tu": 6,
    },
    {
        "ma_danh_muc": "DM07",
        "ten_danh_muc": "Sữa thực vật",
        "mo_ta": (
            "Sữa thực vật là lựa chọn phổ biến cho người ưa chuộng nguồn dinh dưỡng từ thực vật, "
            "cung cấp đạm, vitamin và khoáng chất trong lối sống cân bằng."
        ),
        "noi_bat": "",
        "loai_sua_id": "LS06",
        "thu_tu": 7,
    },
]


THUOC_TINH_DATA = [
    {"ma_thuoc_tinh": "DM01_AGE", "danh_muc_id": "DM01", "ten_thuoc_tinh": "Độ tuổi", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": True, "thu_tu": 1},
    {"ma_thuoc_tinh": "DM01_STAGE", "danh_muc_id": "DM01", "ten_thuoc_tinh": "Giai đoạn", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": False, "thu_tu": 2},
    {"ma_thuoc_tinh": "DM01_PACK", "danh_muc_id": "DM01", "ten_thuoc_tinh": "Đóng gói", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": False, "thu_tu": 3},
    {"ma_thuoc_tinh": "DM02_AGE", "danh_muc_id": "DM02", "ten_thuoc_tinh": "Độ tuổi", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": True, "thu_tu": 1},
    {"ma_thuoc_tinh": "DM02_FLAVOR", "danh_muc_id": "DM02", "ten_thuoc_tinh": "Hương vị", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": False, "thu_tu": 2},
    {"ma_thuoc_tinh": "DM02_PREP", "danh_muc_id": "DM02", "ten_thuoc_tinh": "Cách chế biến", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": False, "thu_tu": 3},
    {"ma_thuoc_tinh": "DM03_TARGET", "danh_muc_id": "DM03", "ten_thuoc_tinh": "Đối tượng sử dụng", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": True, "thu_tu": 1},
    {"ma_thuoc_tinh": "DM03_BENEFIT", "danh_muc_id": "DM03", "ten_thuoc_tinh": "Công dụng chính", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": False, "thu_tu": 2},
    {"ma_thuoc_tinh": "DM03_SUGAR", "danh_muc_id": "DM03", "ten_thuoc_tinh": "Có đường", "kieu_du_lieu": "boolean", "don_vi": "", "bat_buoc": False, "thu_tu": 3},
    {"ma_thuoc_tinh": "DM04_FLAVOR", "danh_muc_id": "DM04", "ten_thuoc_tinh": "Hương vị", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": False, "thu_tu": 1},
    {"ma_thuoc_tinh": "DM04_PROBIOTIC", "danh_muc_id": "DM04", "ten_thuoc_tinh": "Men sống", "kieu_du_lieu": "boolean", "don_vi": "", "bat_buoc": False, "thu_tu": 2},
    {"ma_thuoc_tinh": "DM04_PACK", "danh_muc_id": "DM04", "ten_thuoc_tinh": "Đóng gói", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": False, "thu_tu": 3},
    {"ma_thuoc_tinh": "DM05_VOLUME", "danh_muc_id": "DM05", "ten_thuoc_tinh": "Dung tích", "kieu_du_lieu": "number", "don_vi": "ml", "bat_buoc": True, "thu_tu": 1},
    {"ma_thuoc_tinh": "DM05_SUGAR", "danh_muc_id": "DM05", "ten_thuoc_tinh": "Có đường", "kieu_du_lieu": "boolean", "don_vi": "", "bat_buoc": False, "thu_tu": 2},
    {"ma_thuoc_tinh": "DM05_UHT", "danh_muc_id": "DM05", "ten_thuoc_tinh": "Tiệt trùng", "kieu_du_lieu": "boolean", "don_vi": "", "bat_buoc": False, "thu_tu": 3},
    {"ma_thuoc_tinh": "DM06_WEIGHT", "danh_muc_id": "DM06", "ten_thuoc_tinh": "Khối lượng", "kieu_du_lieu": "number", "don_vi": "g", "bat_buoc": True, "thu_tu": 1},
    {"ma_thuoc_tinh": "DM06_SWEETNESS", "danh_muc_id": "DM06", "ten_thuoc_tinh": "Độ ngọt", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": False, "thu_tu": 2},
    {"ma_thuoc_tinh": "DM06_USE", "danh_muc_id": "DM06", "ten_thuoc_tinh": "Ứng dụng", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": False, "thu_tu": 3},
    {"ma_thuoc_tinh": "DM07_SOURCE", "danh_muc_id": "DM07", "ten_thuoc_tinh": "Nguồn gốc thực vật", "kieu_du_lieu": "text", "don_vi": "", "bat_buoc": True, "thu_tu": 1},
    {"ma_thuoc_tinh": "DM07_CALCIUM", "danh_muc_id": "DM07", "ten_thuoc_tinh": "Bổ sung canxi", "kieu_du_lieu": "boolean", "don_vi": "", "bat_buoc": False, "thu_tu": 2},
    {"ma_thuoc_tinh": "DM07_SUGAR", "danh_muc_id": "DM07", "ten_thuoc_tinh": "Có đường", "kieu_du_lieu": "boolean", "don_vi": "", "bat_buoc": False, "thu_tu": 3},
]


GIA_TRI_THUOC_TINH_DATA = [
    {"sua_id": "S09", "thuoc_tinh_id": "DM01_AGE", "gia_tri_van_ban": "1-3 tuổi"},
    {"sua_id": "S09", "thuoc_tinh_id": "DM01_STAGE", "gia_tri_van_ban": "Stage 3"},
    {"sua_id": "S09", "thuoc_tinh_id": "DM01_PACK", "gia_tri_van_ban": "Lon 800g"},
    {"sua_id": "S02", "thuoc_tinh_id": "DM03_TARGET", "gia_tri_van_ban": "Người lớn cần bổ sung dinh dưỡng"},
    {"sua_id": "S02", "thuoc_tinh_id": "DM03_BENEFIT", "gia_tri_van_ban": "Hỗ trợ cơ xương và sức đề kháng"},
    {"sua_id": "S02", "thuoc_tinh_id": "DM03_SUGAR", "gia_tri_dung_sai": True},
    {"sua_id": "S03", "thuoc_tinh_id": "DM03_TARGET", "gia_tri_van_ban": "Người lớn cần bổ sung năng lượng"},
    {"sua_id": "S03", "thuoc_tinh_id": "DM03_BENEFIT", "gia_tri_van_ban": "Bổ sung năng lượng và vi chất"},
    {"sua_id": "S03", "thuoc_tinh_id": "DM03_SUGAR", "gia_tri_dung_sai": True},
    {"sua_id": "S07", "thuoc_tinh_id": "DM04_FLAVOR", "gia_tri_van_ban": "Tự nhiên"},
    {"sua_id": "S07", "thuoc_tinh_id": "DM04_PROBIOTIC", "gia_tri_dung_sai": True},
    {"sua_id": "S07", "thuoc_tinh_id": "DM04_PACK", "gia_tri_van_ban": "Thùng 48 hộp 100g"},
    {"sua_id": "S01", "thuoc_tinh_id": "DM05_VOLUME", "gia_tri_so": 180},
    {"sua_id": "S01", "thuoc_tinh_id": "DM05_SUGAR", "gia_tri_dung_sai": False},
    {"sua_id": "S01", "thuoc_tinh_id": "DM05_UHT", "gia_tri_dung_sai": True},
    {"sua_id": "S04", "thuoc_tinh_id": "DM05_VOLUME", "gia_tri_so": 180},
    {"sua_id": "S04", "thuoc_tinh_id": "DM05_SUGAR", "gia_tri_dung_sai": False},
    {"sua_id": "S04", "thuoc_tinh_id": "DM05_UHT", "gia_tri_dung_sai": True},
    {"sua_id": "S05", "thuoc_tinh_id": "DM05_VOLUME", "gia_tri_so": 180},
    {"sua_id": "S05", "thuoc_tinh_id": "DM05_SUGAR", "gia_tri_dung_sai": True},
    {"sua_id": "S05", "thuoc_tinh_id": "DM05_UHT", "gia_tri_dung_sai": True},
    {"sua_id": "S06", "thuoc_tinh_id": "DM06_WEIGHT", "gia_tri_so": 100},
    {"sua_id": "S06", "thuoc_tinh_id": "DM06_SWEETNESS", "gia_tri_van_ban": "Đậm"},
    {"sua_id": "S06", "thuoc_tinh_id": "DM06_USE", "gia_tri_van_ban": "Pha cà phê, làm bánh"},
    {"sua_id": "S08", "thuoc_tinh_id": "DM07_SOURCE", "gia_tri_van_ban": "Đậu nành"},
    {"sua_id": "S08", "thuoc_tinh_id": "DM07_CALCIUM", "gia_tri_dung_sai": True},
    {"sua_id": "S08", "thuoc_tinh_id": "DM07_SUGAR", "gia_tri_dung_sai": False},
]


LOAI_SUA_TO_DANH_MUC = {
    "LS01": "DM05",
    "LS02": "DM03",
    "LS03": "DM01",
    "LS04": "DM06",
    "LS05": "DM04",
    "LS06": "DM07",
}


def seed_danh_muc_va_thuoc_tinh(apps, schema_editor):
    DanhMucSanPham = apps.get_model("Milk", "DanhMucSanPham")
    ThuocTinhDanhMuc = apps.get_model("Milk", "ThuocTinhDanhMuc")
    GiaTriThuocTinhSanPham = apps.get_model("Milk", "GiaTriThuocTinhSanPham")
    Sua = apps.get_model("Milk", "Sua")

    for row in DANH_MUC_DATA:
        DanhMucSanPham.objects.update_or_create(
            ma_danh_muc=row["ma_danh_muc"],
            defaults={
                "ten_danh_muc": row["ten_danh_muc"],
                "mo_ta": row["mo_ta"],
                "noi_bat": row["noi_bat"],
                "loai_sua_id": row["loai_sua_id"],
                "thu_tu": row["thu_tu"],
                "hien_thi": True,
            },
        )

    for loai_sua_id, danh_muc_id in LOAI_SUA_TO_DANH_MUC.items():
        Sua.objects.filter(loai_sua_id=loai_sua_id).update(danh_muc_id=danh_muc_id)

    for row in THUOC_TINH_DATA:
        ThuocTinhDanhMuc.objects.update_or_create(
            ma_thuoc_tinh=row["ma_thuoc_tinh"],
            defaults={
                "danh_muc_id": row["danh_muc_id"],
                "ten_thuoc_tinh": row["ten_thuoc_tinh"],
                "kieu_du_lieu": row["kieu_du_lieu"],
                "don_vi": row["don_vi"],
                "bat_buoc": row["bat_buoc"],
                "thu_tu": row["thu_tu"],
            },
        )

    for row in GIA_TRI_THUOC_TINH_DATA:
        GiaTriThuocTinhSanPham.objects.update_or_create(
            sua_id=row["sua_id"],
            thuoc_tinh_id=row["thuoc_tinh_id"],
            defaults={
                "gia_tri_van_ban": row.get("gia_tri_van_ban", ""),
                "gia_tri_so": row.get("gia_tri_so"),
                "gia_tri_dung_sai": row.get("gia_tri_dung_sai"),
            },
        )


def remove_danh_muc_va_thuoc_tinh(apps, schema_editor):
    DanhMucSanPham = apps.get_model("Milk", "DanhMucSanPham")
    ThuocTinhDanhMuc = apps.get_model("Milk", "ThuocTinhDanhMuc")
    GiaTriThuocTinhSanPham = apps.get_model("Milk", "GiaTriThuocTinhSanPham")
    Sua = apps.get_model("Milk", "Sua")

    GiaTriThuocTinhSanPham.objects.filter(
        thuoc_tinh_id__in=[row["ma_thuoc_tinh"] for row in THUOC_TINH_DATA]
    ).delete()
    ThuocTinhDanhMuc.objects.filter(
        ma_thuoc_tinh__in=[row["ma_thuoc_tinh"] for row in THUOC_TINH_DATA]
    ).delete()
    Sua.objects.filter(loai_sua_id__in=LOAI_SUA_TO_DANH_MUC.keys()).update(danh_muc_id=None)
    DanhMucSanPham.objects.filter(
        ma_danh_muc__in=[row["ma_danh_muc"] for row in DANH_MUC_DATA]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Milk', '0010_force_unicode_vietnamese_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucSanPham',
            fields=[
                ('ma_danh_muc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_danh_muc', models.CharField(max_length=100, unique=True)),
                ('mo_ta', models.TextField(blank=True)),
                ('noi_bat', models.CharField(blank=True, max_length=50)),
                ('thu_tu', models.PositiveIntegerField(default=0)),
                ('hien_thi', models.BooleanField(default=True)),
                ('loai_sua', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='danh_muc_san_pham', to='Milk.loaisua')),
            ],
            options={
                'verbose_name': 'Danh muc san pham',
                'verbose_name_plural': 'Danh muc san pham',
                'ordering': ['thu_tu', 'ma_danh_muc'],
            },
        ),
        migrations.CreateModel(
            name='ThuocTinhDanhMuc',
            fields=[
                ('ma_thuoc_tinh', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ten_thuoc_tinh', models.CharField(max_length=100)),
                ('kieu_du_lieu', models.CharField(choices=[('text', 'Van ban'), ('number', 'So'), ('boolean', 'Dung/Sai')], default='text', max_length=20)),
                ('don_vi', models.CharField(blank=True, max_length=20)),
                ('bat_buoc', models.BooleanField(default=False)),
                ('thu_tu', models.PositiveIntegerField(default=0)),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuoc_tinh', to='Milk.danhmucsanpham')),
            ],
            options={
                'verbose_name': 'Thuoc tinh danh muc',
                'verbose_name_plural': 'Thuoc tinh danh muc',
                'ordering': ['danh_muc', 'thu_tu', 'ma_thuoc_tinh'],
            },
        ),
        migrations.CreateModel(
            name='GiaTriThuocTinhSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia_tri_van_ban', models.CharField(blank=True, max_length=255)),
                ('gia_tri_so', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gia_tri_dung_sai', models.BooleanField(blank=True, null=True)),
                ('sua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gia_tri_thuoc_tinh', to='Milk.sua')),
                ('thuoc_tinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gia_tri_san_pham', to='Milk.thuoctinhdanhmuc')),
            ],
            options={
                'verbose_name': 'Gia tri thuoc tinh san pham',
                'verbose_name_plural': 'Gia tri thuoc tinh san pham',
                'ordering': ['sua', 'thuoc_tinh__thu_tu', 'thuoc_tinh_id'],
            },
        ),
        migrations.AddField(
            model_name='sua',
            name='danh_muc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='san_pham', to='Milk.danhmucsanpham'),
        ),
        migrations.AddConstraint(
            model_name='thuoctinhdanhmuc',
            constraint=models.UniqueConstraint(fields=('danh_muc', 'ten_thuoc_tinh'), name='uq_thuoc_tinh_danh_muc_ten'),
        ),
        migrations.AddConstraint(
            model_name='giatrithuoctinhsanpham',
            constraint=models.UniqueConstraint(fields=('sua', 'thuoc_tinh'), name='uq_gia_tri_san_pham_thuoc_tinh'),
        ),
        migrations.RunPython(seed_danh_muc_va_thuoc_tinh, remove_danh_muc_va_thuoc_tinh),
    ]
