# Generated by Django 4.2.8 on 2026-04-26

from django.db import migrations, models


CATEGORY_DISPLAY_DATA = {
    "DM01": {"so_luong_hien_thi": 20, "hien_thi": True, "noi_bat": ""},
    "DM02": {"so_luong_hien_thi": 25, "hien_thi": True, "noi_bat": ""},
    "DM03": {"so_luong_hien_thi": 24, "hien_thi": True, "noi_bat": ""},
    "DM04": {"so_luong_hien_thi": 50, "hien_thi": True, "noi_bat": ""},
    "DM05": {"so_luong_hien_thi": 50, "hien_thi": True, "noi_bat": "Best"},
    "DM06": {"so_luong_hien_thi": 40, "hien_thi": True, "noi_bat": ""},
    "DM07": {"so_luong_hien_thi": 30, "hien_thi": True, "noi_bat": ""},
    "DM08": {"so_luong_hien_thi": 0, "hien_thi": False, "noi_bat": "New"},
}


def seed_category_display_data(apps, schema_editor):
    DanhMucSanPham = apps.get_model("Milk", "DanhMucSanPham")
    for ma_danh_muc, values in CATEGORY_DISPLAY_DATA.items():
        DanhMucSanPham.objects.filter(ma_danh_muc=ma_danh_muc).update(**values)


def rollback_category_display_data(apps, schema_editor):
    DanhMucSanPham = apps.get_model("Milk", "DanhMucSanPham")
    for ma_danh_muc in CATEGORY_DISPLAY_DATA:
        DanhMucSanPham.objects.filter(ma_danh_muc=ma_danh_muc).update(
            so_luong_hien_thi=0,
            hien_thi=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("Milk", "0013_seed_category_image_sets"),
    ]

    operations = [
        migrations.AddField(
            model_name="danhmucsanpham",
            name="so_luong_hien_thi",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_category_display_data, rollback_category_display_data),
    ]
