# Generated by Django 4.2.8 on 2026-04-26

from django.db import migrations, models
import django.db.models.deletion


PRODUCT_DETAIL_DATA = {
    "S01": {
        "mo_ta_chi_tiet": (
            "Duoc san xuat tu sua tuoi sach, ket hop voi cac duong chat thiet yeu nhu dam, "
            "chat beo, carbohydrate, DHA, Omega 3-6, canxi, vitamin va khoang chat. "
            "Ngoai ra, san pham con bo sung GOS/FOS va HMO giup ho tro tieu hoa, tang cuong "
            "mien dich, gop phan phat trien toan dien ve the chat va tri tue."
        ),
        "lua_chon_mua": [
            {
                "ten_lua_chon": "Thung 48 hop",
                "don_gia": 400000,
                "giam_gia": 8,
                "mac_dinh": True,
                "thu_tu": 1,
                "hien_thi": True,
            },
            {
                "ten_lua_chon": "Loc 4 hop",
                "don_gia": 41400,
                "giam_gia": 0,
                "mac_dinh": False,
                "thu_tu": 2,
                "hien_thi": True,
            },
        ],
    }
}


def seed_product_detail_data(apps, schema_editor):
    Sua = apps.get_model("Milk", "Sua")
    LuaChonMuaSua = apps.get_model("Milk", "LuaChonMuaSua")

    for ma_sua, payload in PRODUCT_DETAIL_DATA.items():
        Sua.objects.filter(ma_sua=ma_sua).update(mo_ta_chi_tiet=payload["mo_ta_chi_tiet"])
        LuaChonMuaSua.objects.filter(sua_id=ma_sua).delete()
        for item in payload["lua_chon_mua"]:
            LuaChonMuaSua.objects.create(sua_id=ma_sua, **item)


def rollback_product_detail_data(apps, schema_editor):
    Sua = apps.get_model("Milk", "Sua")
    LuaChonMuaSua = apps.get_model("Milk", "LuaChonMuaSua")

    for ma_sua in PRODUCT_DETAIL_DATA:
        Sua.objects.filter(ma_sua=ma_sua).update(mo_ta_chi_tiet="")
        LuaChonMuaSua.objects.filter(sua_id=ma_sua).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("Milk", "0014_add_category_display_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="sua",
            name="mo_ta_chi_tiet",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="LuaChonMuaSua",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ten_lua_chon", models.CharField(max_length=100)),
                ("don_gia", models.DecimalField(decimal_places=0, max_digits=12)),
                ("giam_gia", models.PositiveSmallIntegerField(default=0)),
                ("mac_dinh", models.BooleanField(default=False)),
                ("thu_tu", models.PositiveIntegerField(default=0)),
                ("hien_thi", models.BooleanField(default=True)),
                ("sua", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lua_chon_mua", to="Milk.sua")),
            ],
            options={
                "ordering": ["thu_tu", "id"],
                "verbose_name": "Lua chon mua sua",
                "verbose_name_plural": "Lua chon mua sua",
            },
        ),
        migrations.RunPython(seed_product_detail_data, rollback_product_detail_data),
    ]
