# Generated by Django 4.2.8 on 2026-04-26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Milk", "0015_product_detail_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="GioHang",
            fields=[
                (
                    "ma_gio_hang",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tao_luc", models.DateTimeField(auto_now_add=True)),
                ("cap_nhat_luc", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-cap_nhat_luc"],
                "verbose_name": "Gio hang",
                "verbose_name_plural": "Gio hang",
            },
        ),
        migrations.CreateModel(
            name="ChiTietGioHang",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("so_luong", models.PositiveIntegerField(default=1)),
                ("tao_luc", models.DateTimeField(auto_now_add=True)),
                ("cap_nhat_luc", models.DateTimeField(auto_now=True)),
                (
                    "gio_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chi_tiet",
                        to="Milk.giohang",
                    ),
                ),
                (
                    "lua_chon_mua",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chi_tiet_gio_hang",
                        to="Milk.luachonmuasua",
                    ),
                ),
                (
                    "sua",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chi_tiet_gio_hang",
                        to="Milk.sua",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "verbose_name": "Chi tiet gio hang",
                "verbose_name_plural": "Chi tiet gio hang",
            },
        ),
        migrations.AddConstraint(
            model_name="chitietgiohang",
            constraint=models.UniqueConstraint(
                fields=("gio_hang", "sua", "lua_chon_mua"),
                name="unique_cart_item_per_option",
            ),
        ),
    ]
